# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('mode', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('mode', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=0)),
                ('degree', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('duration', models.IntegerField(default=0)),
            ],
        ),
    ]
