# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.FloatField(default=0),
        ),
    ]
