# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0002_auto_20161025_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration_id',
            field=models.IntegerField(default=0),
        ),
    ]
