# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0003_course_duration_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sector',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sector1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sector2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sector3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sector4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='sector5',
            field=models.IntegerField(default=0),
        ),
    ]
