# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0005_auto_20161124_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='levelStr',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='course',
            name='modeStr',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='course',
            name='sectorStr',
            field=models.CharField(default='', max_length=60),
        ),
    ]
