# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0006_auto_20161125_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='sectorStrMap',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='levelStr',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='modeStr',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='course',
            name='sectorStr',
            field=models.CharField(max_length=60),
        ),
    ]
