# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0008_remove_course_sectorstrmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='degreeStr',
            field=models.CharField(default='', max_length=60),
        ),
    ]
