# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0009_course_degreestr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degreeStr',
            field=models.CharField(max_length=60),
        ),
    ]
