# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0010_auto_20161125_0510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.IntegerField(default=0)),
                ('courseId', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
